### ISSUE TITLE
Convert to native reason executable

### ISSUE THREAD

**Issue by bryphe** [bryphe/esy-bash#16]
This code just spins up a process w/ some environment variables - should be feasible to do this as a native reason executable (with much faster perf!)

**Comment by ulrikstrid** [comment]
Is it this file: `bin/esy-bash.js`?

**Comment by prometheansacrifice** [comment]
@ulrikstrid I think all the js (index.js, bash-exec etc) need to be converted to reason so that we can avoid node's overhead.

**Comment by prometheansacrifice** [comment]
@ulrikstrid and @bryphe Can I take this one up? I'll definitely need help and will not hesitate to reach out to you guys. This is only if it can wait for sometime, because I might be a bit slow :)

**Comment by bryphe** [comment]
@prometheansacrifice - would love to have help with this! 💯 Thanks for offering to pick it up. It will be a significant perf improvement for `esy` on Windows, because `esy-bash` is called quite a bit, and every time we pay a node start-up tax today.

It'd also be a neat example to show users how they can use Reason to speed up their tools.

Keep us posted if you need anything!

**Comment by bryphe** [comment]
This is now complete thanks to @prometheansacrifice 's awesome contribution in #19 🎉
