### ISSUE TITLE
Native EsyBash: 'ls' command doesn't work

### ISSUE THREAD

**Issue by bryphe** [bryphe/esy-bash#24]
With the native version of `esy-bash`, the `ls` command doesn't work:
```
E:\esy-bash\re\_build\default\bin [master ≡ +1 ~0 -0 !]> ./EsyBash.exe ls -a
C:\Users\bryph\AppData\Local\Temp\__esy-bash__79677993__1__.sh: line 2: ls: command not found
```

However, this works correctly with the node version:
```
E:\esy-bash [master ≡ +1 ~0 -0 !]> node .\bin\esy-bash.js ls -a
.        .git         __tests__     bin              jest.config.js  package.json       re
..       .gitignore   appveyor.yml  index.js         LICENSE         package-lock.json  README.md
.cygwin  .travis.yml  bash-exec.js  install-opam.sh  node_modules    postinstall.js
```

It looks like the difference is that the JS version is somehow including `/usr/local/bin` and /usr/bin` in the PATH, whereas the native version is not. I'm not sure if this is some difference in how we spin up the bash process? We'll need to make sure these are included in the PATH

**Comment by prometheansacrifice** [comment]
Weird. Works fine here.

```
c:\Users\manas\development\esy-bash\re>.\_build\default\bin\EsyBash.exe ls
_build  appveyor.yml  dune-project      esy-bash.opam  lib           package.json
_esy    bin           esy-bash.install  esy.lock.json  node_modules  tests
```

**Comment by prometheansacrifice** [comment]
Turnout it was because of cygwin on my path that didn't let me know of this issue.

**Comment by bryphe** [comment]
> Turnout it was because of cygwin on my path that didn't let me know of this issue.

Oh interesting, so it picked up the other cygwin install - thanks for the help with this @prometheansacrifice !

**Comment by prometheansacrifice** [comment]
Writing tests for this will be a little tricky since the cygwin binaries are already on the path when run in the test environment.

**Comment by bryphe** [comment]
Thanks for the fix @prometheansacrifice !

> Writing tests for this will be a little tricky since the cygwin binaries are already on the path when run in the test environment.

This is because we'd run the tests via `esy b dune runtest`? So the paths already get included by `esy`?

One alternative would be to continue using node/javascript for our tests - we could run those outside of the esy sandbox. We'd just have to change the way that we invoke esy-bash - using our executable instead of the JS script.

**Comment by bryphe** [comment]
Thanks for the fix, @prometheansacrifice ! Verified it works now (and we have integrated `esy-bash` native with `master` on esy! 🎉 )
