### ISSUE TITLE
MinGW gcc vs gcc?

### ISSUE THREAD

**Issue by phated** [bryphe/esy-bash#56]
What's the intention/difference between the `x86_64-w64-mingw32-gcc` installed by esy-bash and the normal `gcc` package you can install with Cygwin?

I'm trying to build CMake from source and it fails because their bootstrap detects Cygwin but then tries to compile (when forced) with `mingw`.

I'm currently attempting to install `gcc` with Cygwin and then build CMake from source. Will update with results.

**Comment by ManasJayanth** [comment]
Binaries output by `x86_64-w64-mingw32-gcc` dont need the cygwin.dll

Anything built with plain gcc inside cygwin needs a small runtime (cyginw.dll) to emulate the unix/posix layer.

**Comment by ManasJayanth** [comment]
> I'm trying to build CMake from source and it fails because their bootstrap detects Cygwin but then tries to compile (when forced) with mingw.

This is intentional so that resulting binary wouldnt need cygwin runtime.

**Comment by phated** [comment]
@ManasJayanth I didn't know that, but it that makes sense! I'll close this.

However, I think we need to trick CMake into realizing that it is running with MinGW instead of Cygwin (it calls uname to determine that) otherwise it won't build successfully.
